server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: 1234
    
#  mvc:
#    view:
#      pom.xml에 mastache의존성 삽입으로 기본설정 되어있어 생략 가능    
#      prefix: /templates/
#      suffix: .mustache

  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    
  security:
    oauth2:
      client:
        registration:
          google:
              client-id: 693251242852-0bbnt7pg2a1i55sidijleiht881rop1r.apps.googleusercontent.com
              client-secret: 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
              scope:
              - email
              - profile
              
          facebook:
              client-id: 2869409373190987
              client-secret: 1481358750183d97fd631f9aa70dd4ce
              scope:
              - email
              - public_profile       
          
          naver:
            client-id: Vts7CjHXjzt88wqNY_dn
            client-secret: bXUioYJzZp
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/naver
            
        provider: 
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌